jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04

        ${{ if parameters.cross }}:
          MacOs:
            vmImage: macOS-10.13
          Windows:
            vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)

    steps:
      - template: azure-install-rust.yml
        parameters:
          rust_version: ${{ parameters.rust.version }}
          components: ${{ parameters.rust.components }}

#      - template: azure-install-dependencies.yml

      - template: azure-clone-patch-otp.yml

      - script: cargo build --tests
        env:
          CI: 'True'
        displayName: cargo build --tests

      - ${{ each crate in parameters.crates }}:
          - script: cargo test
            env:
              CI: 'True'
            displayName: ${{ crate.key }} - cargo test
            workingDirectory: $(Build.SourcesDirectory)/${{ crate.key }}
